### ISSUE TITLE
Can not set Hospital Leader

### ISSUE THREAD

**Issue by SupperCraft5000** [edouardlicn/Ifxoss_ragemp#1]
When i try the command "/sethospitalleader" or "/sethospitalleader 1" then nothing happend the Database is not changed. And there is a error on the console.
`(node:5356) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: s.getAdminLvl is not a function
(node:5356) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5356) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: s.getAdminLvl is not a function`

**Comment by edouardlicn** [comment]
this is not originally create by me that i don't have the ability to fix that bug.may be you ask the original author in readme.md better.i can update here when he fix.

**Comment by edouardlicn** [comment]
BTW,you make a barbershop but did not set the cord?

**Comment by edouardlicn** [comment]
if you not add cord i will delete it.for it will not work and become bug.
